### ISSUE TITLE
Question: Should we display in problem's view the error generated from LSP for the local-history file

### ISSUE THREAD

**Issue by lmcbout** [vince-fugnitto/local-history-ext#168]
**Bug Description**
Question:
Should we parse the file in local history to provide some error | warning | info in the problem's view.
Currently, If I open the file from local-history view, it compares the file in workspace with file in local-history. Both sides report information in the problems view, but the info reported are different. 

**Steps to Reproduce**
- Use a cpp project (I used Bird-Flocking-simm-tbb from Vince)
- Modify a header file (Bird.h)
--> This generates a file in local history
- Open the file in local-history
--> See in problem view, there are errors reported for each side of the diff editor, but the error are differents.

--> Look at the picture, I open Boild.h (Workspace file and the local-history file)

![DiffEditorClangProblem](https://user-images.githubusercontent.com/419051/85033717-45cfcb00-b14f-11ea-8760-4688fe308568.png)

**Comment by vince-fugnitto** [comment]
@lmcbout the behavior is normal is it not? For the left hand-side (local history) the errors are different since the file is outside the workspace and thus stuff like `imports` cannot be resolved.

The `diff` api is from vscode and in vscode they also show the markers for both sides, there is no way to control this behavior from an extension.

**Comment by lmcbout** [comment]
Thanks for the info
